### ISSUE TITLE
import ask_sdk_core doesn't work - 'no module named...'

### ISSUE THREAD

**Issue by Huligan2** [alexa/skill-sample-python-first-skill#12]
Hi,
I've successfully written Lambda Python 2.7 code to handle a conversation, but am now looking to do some new stuff & tried following this GitHub example but failed at the first hurdle.  The imports of ask_sdk_* fail.  All of this is being done within the AWS Lamdba Management Console.

I thought when you're within the Lambda environment that all the the Alexa sdk's were all installed.

Please can someone tell me what the obvious step is that I've missed.  I'm clearly missing something

Thanks in advance!

**Comment by JoeMoCode** [comment]
Hi Huligan2, my suspicion is you do not have the ASK dependency in your lambda runtime. You can try to use Alexa Hosted in the developer.amazon.com ASK console, or you will need to manually upload the dependency. 

Since this is not an issue with this repository, I will resolve this, but if you are still having problems, please reach out over alexa.design/contactus or on the Alexa developer forums: https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html
