### ISSUE TITLE
Incorrect single and double quotes in code blocks in Markdown files

### ISSUE THREAD

**Issue by mrsnooty** [alexa/skill-sample-python-first-skill#15]
Following along using the instructions in the 4 modules, I ran into errors testing the skill.
Eventually I figure out this is due to some of the sample code blocks in the Markdown files containing curvy single or double quotes (aka "smart quotes"), instead of ' and "

**Comment by dustindaon** [comment]
This is possibly from these lines inside of def handle() in HasBirthdayLaunchRequestHandler:
year = attr['year']
month = attr['month'] # month is a string, and we need to convert it to a month index later
day = attr['day']

I got this error
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': invalid character in identifier (lambda_function.py, line 56)
Traceback (most recent call last):
File "/var/task/lambda_function.py" Line 56
year = attr[‘year’]

Which can be fixed by changing out the quotation marks to double quotes ie:
year = attr["year"]
month = attr["month"] # month is a string, and we need to convert it to a month index later
day = attr["day"]

**Comment by ajot** [comment]
Fixed with https://github.com/alexa/skill-sample-python-first-skill/commit/2dc1356f7d71fcea11773c7867009f705de66cd8
