### ISSUE TITLE
There was a problem connecting to the service

### ISSUE THREAD

**Issue by Jobin-S** [alexa/skill-sample-python-first-skill#41]
I do all thing and showing "There was a problem connecting to the service"
![image](https://user-images.githubusercontent.com/63976083/86910085-beb2b900-c136-11ea-80cb-ea7607f5e129.png)

**Comment by meltwater2000** [comment]
Also had similar issue.

Debugging suggests an issue with the get.requests call with url= '{api_endpoint}/v2/devices/{device_id}/settings/System.timeZone'.

If you skip this and hard-code the timezone:
now_time = datetime.now(timezone("Europe/London"))

You can at least continue with the rest of the tutorial.  However, interested to know what the fix is.

**Comment by DaveCalaway** [comment]
I have the same problem 😭

**Comment by scorpiontornado** [comment]
After doing some research, I found a [response from Amazon](https://forums.developer.amazon.com/comments/233709/view.html) which states that "it is not possible to access the Settings API from the developer console". Hopefully they'll fix it soon...

**Comment by aszk** [comment]
Like @scorpiontornado mentioned above, there are some limitations on Alexa Simulator. Please use your Echo device for testing.   
https://developer.amazon.com/en-US/docs/alexa/devconsole/alexa-simulator.html#alexa-simulator-limitations
