### ISSUE TITLE
module 3 for python(lambda_function.py) isnt working

### ISSUE THREAD

**Issue by nihalnalla** [alexa/skill-sample-python-first-skill#5]
I have gone through this complete process step by step (https://developer.amazon.com/en-US/alexa/alexa-skills-kit/resources/training-resources/cake-walk/cake-walk-5) and now the code isnt working.
 --> It worked well when i did with the previous module.
error:
in the aleca developer console, test tab

user: Alexa open cake walk
alexa: Sorry, I couldn't understand what you said. Please try again.

please address this at the earliest.
thanks

**Comment by vikash010** [comment]
@nihalnalla  just go to media storage and find the bucket name which is something like this "amzn1-ask-skill-78d6-etc-etc"  copy it and replace the "S3-BUCKET-NAME" with the copied string 
s3_adapter = S3Adapter(bucket_name="S3-BUCKET-NAME")  

And let me know if it solve  . this issue is solved here
 https://github.com/alexa/skill-sample-python-first-skill/issues/2

**Comment by nihalnalla** [comment]
hey thanks, it fixed the problem
